### PR TITLE
New book for custom eslint plugins

### PR DESCRIPTION
**Pull request by Jarmahent**
#3

### CODE REVIEW

**Comment by davidgatti** [comment]
@Jarmahent who should review this PR? :)

**Comment by Jarmahent** [comment]
@davidgatti I never know you can assign someone to review a pr but thanks and sorry!

**Comment by davidgatti** [comment]
@Jarmahent Don't say sorry, the point is for me to show you, so no stress :)

**Comment by davidgatti** [comment]
@Jarmahent just a friendly reminder :)

**Comment by Jarmahent** [comment]
@davidgatti  I have added a small overview regarding yeoman and generator-eslint :)

**Pull request merged**
